# Generated by Django 5.0.3 on 2024-03-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspaper",
            name="topic",
        ),
        migrations.AddField(
            model_name="newspaper",
            name="topic",
            field=models.ManyToManyField(
                related_name="newspapers", to="newspaper.topic"
            ),
        ),
    ]
