# Generated by Django 5.0.3 on 2024-03-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_remove_newspaper_topic_newspaper_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspaper',
            old_name='topic',
            new_name='topics',
        ),
    ]
