# Generated by Django 5.0.3 on 2024-03-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_rename_topic_newspaper_topics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ['-published_date']},
        ),
    ]
